# Generated by Django 2.1.4 on 2019-01-03 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0002_auto_20181230_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='updated',
        ),
    ]
